#+TITLE:       the bash profile: a basic setup
#+AUTHOR:      nnungester
#+EMAIL:       nnungester@nnungester-mbp.local
#+DATE:        2018-09-30 Sun
#+URI:         /blog/%y/%m/%d/the-bash-profile-a-basic-setup
#+KEYWORDS:    setup, beginner
#+TAGS:        setup, bash
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: a primer to getting a comfy terminal
** Foreword
/If you already know what a bash\_profile is and how to use one. This page isn't
for you. This also is just a short and sweet, I'm not going to go into the details of the differences between a .bashrc and a .bash_profile./

*What is this and why do I need one?*: because you. Down the road you are going to complain about how much typing you have to do, or how hard it is to get setup and working. A bash profile or bashrc allows you to store custom settings for your shell session.  

Below are a couple ways to set up your bash\_profile. I'm basing this off my personal one so take this setup with a grain of salt. Also, this is mainly a setup for MacOS. I'll cover linux later. 
This can be done a variety of ways, here are two (of many potential) differing options: 

** Option 1 .. a single file

Create a file called ~/.bash\_profile and add these contents:

#+NAME: singlefile
#+BEGIN_SRC bash
#!/bin/bash
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\n\$ "
export CLICOLOR=1
export LSCOLORS="ExFxBxDxCxegedabagacad"
export PATH=$HOME/bin:$HOME/.local/bin:$PATH
#-----
# custom additions
#-----
# example
# export GOPATH=$HOME/go
#+END_SRC

then `source ~/.bash_profile`
** Option 2 .. a split file

Though my setup changes from time to time, I generally setup my structure as follows:
#+BEGIN_SRC text
. $HOME
├── .bash_profile
└── .bash_profile.d
    ├── core.sh
    └── development.sh
#+END_SRC
We can setup this structure with the following:

#+NAME: setup
#+BEGIN_SRC bash

cd
mkdir ~/.bash_profile.d
touch {.bash_profile,.bash_profile.d/core.sh,.bash_profile.d/development.sh}

#+END_SRC

For your ~/.bash_profile: 

#+NAME: profile
#+BEGIN_SRC bash

#!/usr/bin/env bash

for f in $HOME/.bash_profile.d/*.sh
do
        . ${f}
done
#+END_SRC

Core to me is anything that I want to keep and hold on to for future uses. Any
aliases,helpers and custom functions go here for me. The following just gets you
a path and pretty prompt.

For your ~/.bash\_profile.d/core.sh:

#+NAME: BashCore
#+BEGIN_SRC bash

#!/bin/bash
# PS1 line below gives you a fancy prompt. Which starts you an a clean line below your pwd..
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\n\$ "
export CLICOLOR=1
export LSCOLORS="ExFxBxDxCxegedabagacad"
export PATH=$HOME/bin:$HOME/.local/bin:$PATH

#+END_SRC

development.sh just includes anything work / job function related for me. any third party settings go here:

For your ~/.bash\_profile.d/development.sh:

#+NAME: Development
#+BEGIN_SRC bash

#!/bin/bash
# example 
export GOPATH=$HOME/go

#+END_SRC

then `source ~/.bash_profile`
** Notes and stuff 

Go crazy with it. Organize this however you want. Alias all the things. That's how you become l33t.

Links to more info about profiles in general:

https://apple.stackexchange.com/questions/51036/what-is-the-difference-between-bash-profile-and-bashrc

https://unix.stackexchange.com/questions/38175/difference-between-login-shell-and-non-login-shell/46856#46856
