#+TITLE:       osx: install spacemacs and spf13vim
#+AUTHOR:      nnungester
#+EMAIL:       nnungester@nnungester-mbp.local
#+DATE:        2018-09-30 Sun
#+URI:         /blog/%y/%m/%d/text-editor-battle
#+KEYWORDS:    vim, emacs, spacemacs, spf13vim
#+TAGS:        vim, emacs
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: getting setup with vim and emacs
** age old battle

Many verbal battles have been waged in the fight between vim and emacs. I suck at both, so I cant really pick a side. Due to me barely finding my way out of vim, yet needing some sparkles while using it, I opt for using a distro. 

For Vim I use Steve Francia's SPF13-vim https://github.com/spf13/spf13-vim  

And for Emacs I use spacemacs. http://spacemacs.org/

People argue that using a distro causes you to not fully "learn" vim, or emacs.. I don't really buy that, and I don't think you should either. If you would like to learn the ins and outs of vim, there are plenty of online vim tutors - even vim games. Just get in the habit of using it for simple things over pico or nano. Start bite sized. Don't assume you'll be able to drop your ide for vim right away.  

Before you dive into spacemacs, you should probably learn the basics of vim (switching modes, moving around the text, editing, inserting, saving and exiting). I really only use spacemacs for writing tasks like blogging or writing notes. I looked far and wide for something better to use than markdown and org-mode stood out. Org mode, for now at least, is really the only reason I use emacs.

** installation
Vim:
#+NAME: vim install
#+BEGIN_SRC bash
# vim install with spf13-vim
brew install vim --with-lua
curl http://j.mp/spf13-vim3 -L -o - | sh
#+END_SRC

Emacs: 
#+NAME: emacs install
#+BEGIN_SRC bash
# emacs install with spacemacs
brew tap d12frosted/emacs-plus
brew install emacs-plus
brew linkapps emacs-plus
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
#+END_SRC

** vimrc.local vimrc.vless

Instead of editing the config for spf13 .. you should create a ~/.vimrc.local file:

#+NAME: vimrc.local
#+BEGIN_SRC vimscript
set nocompatible            
let g:is_bash = 1
set background=dark          
filetype plugin indent on    
set foldmethod=manual
syntax on                    
set mouse=a                  
set mousehide                
scriptencoding utf-8         
set conceallevel=0
au FileType markdown setl conceallevel=0
let g:indentLine_fileTypeExclude=['markdown']
au BufRead,BufNewFile *.md setlocal textwidth=80
#+END_SRC

I like to use vim as a pager from time to time here is a config I took from [[http://vim.wikia.com/wiki/Using_vim_as_a_syntax-highlighting_pager][vim.wikia.com]]

Set the following in your bashrc or profile:

#+NAME: bash config
#+BEGIN_SRC bash
# to pipe into the pager: curl cheat.sh/markdown?T | vpless
alias vpless="vim -u $HOME/.vimrc.vless -"
# otherwise: vless bacon.txt
alias vless="vim -u ~/.vimrc.vless"
# start vim without a config (usefull for learning!) cvim for "clean vim"
alias cvim="vim -u NONE"
#+END_SRC

Create a file named vimrc.vless in your home directory and paste the following in:
/note: on osx copy the following block and at your terminal do `pbpaste > ~/.vimrc.vless`/

#+NAME: vimrc.vless
#+BEGIN_SRC vimscript

" No compatibility – necessary for mappings to work.
set nocompatible

" Status line
set laststatus=0
set cmdheight=1
set nomodifiable 
set readonly
 
set background=dark

" Turn syntax on
syntax enable

" No menu bar nor tool bar
set guioptions=aiMr

" Key bindings.
nmap b <C-B><C-G>
nmap q :q!<CR>
nmap <Up> <C-Y>
nmap <Down> <C-E>

" To type the following line, type *two* C-V's followed by two spaces. This
" is how you map the spacebar.
nmap ^V <C-F><C-G>"

#+END_SRC
